#!/bin/bash
#PBS -l ncpus=16
#PBS -l mem=88GB
#PBS -l vmem=88GB
#PBS -l walltime=48:00:00
#PBS -o $HOME/.jobs/PBS_julia.o
#PBS -V
#PBS -j oe
#PBS -M bhar9988@uni.sydney.edu.au
#PBS -m ae

file="/import/taiji1/bhar9988/code/BaselinePCALab.jl/scripts/calculations/generate_projections.jl"

chmod u+x $file
source ~/.jobtunnel.sh
bash $file 2>&1 | tee /suphys/bhar9988/.jobs/${PBS_JOBID}.log
exit
