#!/bin/bash
#PBS -l select=1:ncpus=32:mem=200GB:vmem=200GB
#PBS -l walltime=96:00:00
#PBS -o $HOME/.jobs/PBS_julia.o
#PBS -V
#PBS -j oe
#PBS -M bhar9988@uni.sydney.edu.au
#PBS -m ae

# JULIA_DISTRIBUTED=true
#file="$WORKDIR/code/DDC/SpatiotemporalMotifs/scripts/calculations/cluster/lower_theta_calculations.jl"
# file="$WORKDIR/code/DDC/SpatiotemporalMotifs/scripts/plots/csd_layer_test.jl"
file="$WORKDIR/code/DDC/SpatiotemporalMotifs/scripts/calculations/collect_calculations.jl"

chmod u+x $file
$file 2>&1 | tee /suphys/bhar9988/.jobs/${PBS_JOBID}.log
exit
