#!/bin/bash
#PBS -l ncpus=16
#PBS -l mem=88GB
#PBS -l vmem=88GB
#PBS -l walltime=48:00:00
#PBS -o $HOME/.jobs/PBS_julia.o
#PBS -V
#PBS -j oe
#PBS -M bhar9988@uni.sydney.edu.au
#PBS -m ae

# JULIA_DISTRIBUTED=true
# file="/suphys/bhar9988/code/DDC/WorkingRegime.jl/WRCircuit.jl/scripts/calculations/critical_sweep.jl"
file="/suphys/bhar9988/code/DDC/WorkingRegime.jl/WRCircuit.jl/scripts/calculations/critical_sweep.jl"
# file="$WORKDIR/code/DDC/WorkingRegime.jl/WRCircuit.jl/scripts/plots/critical_demo.jl"
# file="$WORKDIR/code/BaselinePCALab.jl/nonstationary_processes_lab"

chmod u+x $file
source ~/.jobtunnel.sh
bash $file 2>&1 | tee /suphys/bhar9988/.jobs/${PBS_JOBID}.log
exit
