#! /bin/bash
EXISTS=`qstat -u bhar9988 | grep -o code-phys`
if [ -z "$EXISTS" ]; then
	qsub "$@" /headnode2/bhar9988/code-physics/code-physics.pbs
else
	echo "code-physics already exists. Please delete this job before starting a new one"
fi
