#! /bin/bash
user="$(whoami)"
hostname="$user@headnode.physics.usyd.edu.au"
echo "Connecting to $hostname"
mkdir -p ~/jobs/
ssh $hostname "qsub -o $HOME/jobs/PBS_code-physics.o ~/code-physics/code-physics.pbs"
rm -f ~/code-physics/code-physics.log
touch ~/code-physics/code-physics.log
tail -f ~/code-physics/code-physics.log
