#! /bin/bash
workdir="$HOME/.vscode/cli/"
name="code-physics"
queue="defaultQ"

extra_args=()
while [[ $# -gt 0 ]]; do
    case $1 in
        -w|--workdir)
            workdir="$2"
            shift 2
            ;;
        -n|--name)
            name="$2"
            shift 2
            ;;
        -q|--queue)
            queue="$2"
            shift 2
            ;;
        *)
            extra_args+=("$1")
            shift
            ;;
    esac
done

user="$(whoami)"
hostname="$user@headnode.physics.usyd.edu.au"
mkdir -p ~/jobs/
rm -f ~/code-physics/$name.log
touch ~/code-physics/$name.log
sshcmd="/bin/bash -c \"export workdir='$workdir'; export name='$name'; qsub -o '$HOME/jobs/PBS_code-physics.o' -v workdir,name -q '$queue' ${extra_args[*]} ~/code-physics/code-physics.pbs\""
# sshcmd="/bin/bash -c \"qsub -o '$HOME/jobs/PBS_code-physics.o' -q '$queue' ~/code-physics/code-physics.pbs\""
targethost="${hostname#*@}"
if [[ "$(hostname -f)" == "$targethost" ]]; then
    eval "$sshcmd"
else
    echo "Connecting to $hostname"
    ssh $hostname $sshcmd
fi
tail -f ~/code-physics/$name.log
